version: "2"

services:

  database-server:
    build:
      context: ./database-server
    volumes:
      - ./database-server/init:/docker-entrypoint-initdb.d

  message-queue-server:
    image: rabbitmq:3.7.4-management
    restart: always
    ports:
      - 15672:15672

  task-worker:
    build:
      context: ./task-worker
    tty: true
    volumes:
      - ./task-worker:/work
    command: bash startup.sh
    depends_on:
      - message-queue-server
      - database-server

  app-server:
    build:
      context: ./app-server
    env_file: .env
    command: node build/main.js
    volumes:
      - ./app-server:/home/server
    depends_on:
      - task-worker

  http-server:
    image: nginx:1.12.2
    volumes:
      - ./app-client/dist:/usr/share/nginx/html
      - ./http-server/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./http-server/startup.sh:/startup.sh
    ports:
      - 8080:80
    depends_on:
      - app-server
    environment:
      - APPSERVER_HOST=app-server
    env_file: .env
    command: bash /startup.sh
